services:
  postgres:
    image: postgres:16-alpine
    container_name: svt-postgres
    environment:
      POSTGRES_DB: svt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
