create table if not exists room (
    id varchar(255) primary key,
    type varchar(255),
    mode varchar(255),
    seed bigint not null,
    status varchar(255),
    created_at timestamp(6),
    date_bucket date
);

create table if not exists game_session (
    id varchar(255) primary key,
    room_id varchar(255) not null,
    player_token varchar(255) not null,
    player_name varchar(255),
    game_state_data text,
    completed boolean not null,
    created_at timestamp(6),
    last_action_at timestamp(6),
    version bigint not null
);

create table if not exists leaderboard_entry (
    id bigint generated by default as identity primary key,
    player_name varchar(255),
    team_name varchar(255),
    turns integer not null,
    victory boolean not null,
    last_location varchar(255),
    location_index integer not null,
    total_locations integer not null,
    loss_reason varchar(255),
    health integer not null,
    energy integer not null,
    morale integer not null,
    cash integer not null,
    food integer not null,
    compute_credits integer not null,
    score integer not null,
    weighted_score integer not null,
    elapsed_ms bigint not null,
    daily_run boolean not null,
    game_mode varchar(255),
    created_at timestamp(6)
);

create index if not exists idx_game_session_player_token_completed_last_action
    on game_session (player_token, completed, last_action_at desc);

create index if not exists idx_game_session_room_player
    on game_session (room_id, player_token);

create index if not exists idx_room_type_mode_date_bucket
    on room (type, mode, date_bucket);

create index if not exists idx_leaderboard_non_daily_weighted_score
    on leaderboard_entry (daily_run, weighted_score desc);

create index if not exists idx_leaderboard_daily_created_weighted
    on leaderboard_entry (daily_run, created_at, weighted_score desc);
